export default {
  GET_PROPERTIES: "GET_PROPERTIES",
  GET_PROPERTY: "GET_PROPERTY",
  SET_PROPERTIES: "SET_PROPERTIES",
  SET_PROPERTY: "SET_PROPERTY",
  ADD_PROPERTY: "ADD_PROPERTY",
  UPDATE_PROPERTY: "UPDATE_PROPERTY",
  DELETE_PROPERTY: "DELETE_PROPERTY",
};
