export default {
  GET_USERS: "GET_USERS",
  SET_USERS: "SET_USERS",
  GET_USER: "GET_USER",
  SET_USER: "SET_USER",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  GET_USER_PROFILE: "GET_USER_PROFILE",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  DELETE_USER_PROFILE: "DELETE_USER_PROFILE",
};
